[00;33m 	'cuda/11.3' does not supports the {CUDA_MPI}. [0m
[00;34m 	{CUDA_MPI} is only supported in cuda 11.4 version. [0m
Traceback (most recent call last):
  File "cifar10_deepspeed.py", line 248, in <module>
    model_engine, optimizer, trainloader, __ = deepspeed.initialize(
  File "/home01/hpc72a03/.conda/envs/lightning/lib/python3.8/site-packages/deepspeed/__init__.py", line 124, in initialize
    engine = DeepSpeedEngine(args=args,
  File "/home01/hpc72a03/.conda/envs/lightning/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 261, in __init__
    self._do_args_sanity_check(args)
  File "/home01/hpc72a03/.conda/envs/lightning/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 911, in _do_args_sanity_check
    assert (
AssertionError: DeepSpeed requires --deepspeed_config to specify configuration file
srun: error: gpu15: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "cifar10_deepspeed.py", line 248, in <module>
    model_engine, optimizer, trainloader, __ = deepspeed.initialize(
  File "/home01/hpc72a03/.conda/envs/lightning/lib/python3.8/site-packages/deepspeed/__init__.py", line 124, in initialize
    engine = DeepSpeedEngine(args=args,
  File "/home01/hpc72a03/.conda/envs/lightning/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 261, in __init__
    self._do_args_sanity_check(args)
  File "/home01/hpc72a03/.conda/envs/lightning/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 911, in _do_args_sanity_check
    assert (
AssertionError: DeepSpeed requires --deepspeed_config to specify configuration file
Traceback (most recent call last):
  File "cifar10_deepspeed.py", line 248, in <module>
    model_engine, optimizer, trainloader, __ = deepspeed.initialize(
  File "/home01/hpc72a03/.conda/envs/lightning/lib/python3.8/site-packages/deepspeed/__init__.py", line 124, in initialize
    engine = DeepSpeedEngine(args=args,
  File "/home01/hpc72a03/.conda/envs/lightning/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 261, in __init__
    self._do_args_sanity_check(args)
  File "/home01/hpc72a03/.conda/envs/lightning/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 911, in _do_args_sanity_check
    assert (
AssertionError: DeepSpeed requires --deepspeed_config to specify configuration file
Traceback (most recent call last):
  File "cifar10_deepspeed.py", line 248, in <module>
    model_engine, optimizer, trainloader, __ = deepspeed.initialize(
  File "/home01/hpc72a03/.conda/envs/lightning/lib/python3.8/site-packages/deepspeed/__init__.py", line 124, in initialize
    engine = DeepSpeedEngine(args=args,
  File "/home01/hpc72a03/.conda/envs/lightning/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 261, in __init__
    self._do_args_sanity_check(args)
  File "/home01/hpc72a03/.conda/envs/lightning/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 911, in _do_args_sanity_check
    assert (
AssertionError: DeepSpeed requires --deepspeed_config to specify configuration file
Traceback (most recent call last):
  File "cifar10_deepspeed.py", line 248, in <module>
    model_engine, optimizer, trainloader, __ = deepspeed.initialize(
  File "/home01/hpc72a03/.conda/envs/lightning/lib/python3.8/site-packages/deepspeed/__init__.py", line 124, in initialize
    engine = DeepSpeedEngine(args=args,
  File "/home01/hpc72a03/.conda/envs/lightning/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 261, in __init__
    self._do_args_sanity_check(args)
  File "/home01/hpc72a03/.conda/envs/lightning/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 911, in _do_args_sanity_check
    assert (
AssertionError: DeepSpeed requires --deepspeed_config to specify configuration file
Traceback (most recent call last):
  File "cifar10_deepspeed.py", line 248, in <module>
    model_engine, optimizer, trainloader, __ = deepspeed.initialize(
  File "/home01/hpc72a03/.conda/envs/lightning/lib/python3.8/site-packages/deepspeed/__init__.py", line 124, in initialize
    engine = DeepSpeedEngine(args=args,
  File "/home01/hpc72a03/.conda/envs/lightning/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 261, in __init__
    self._do_args_sanity_check(args)
  File "/home01/hpc72a03/.conda/envs/lightning/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 911, in _do_args_sanity_check
    assert (
AssertionError: DeepSpeed requires --deepspeed_config to specify configuration file
Traceback (most recent call last):
  File "cifar10_deepspeed.py", line 248, in <module>
    model_engine, optimizer, trainloader, __ = deepspeed.initialize(
  File "/home01/hpc72a03/.conda/envs/lightning/lib/python3.8/site-packages/deepspeed/__init__.py", line 124, in initialize
    engine = DeepSpeedEngine(args=args,
  File "/home01/hpc72a03/.conda/envs/lightning/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 261, in __init__
    self._do_args_sanity_check(args)
  File "/home01/hpc72a03/.conda/envs/lightning/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 911, in _do_args_sanity_check
    assert (
AssertionError: DeepSpeed requires --deepspeed_config to specify configuration file
Traceback (most recent call last):
  File "cifar10_deepspeed.py", line 248, in <module>
    model_engine, optimizer, trainloader, __ = deepspeed.initialize(
  File "/home01/hpc72a03/.conda/envs/lightning/lib/python3.8/site-packages/deepspeed/__init__.py", line 124, in initialize
    engine = DeepSpeedEngine(args=args,
  File "/home01/hpc72a03/.conda/envs/lightning/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 261, in __init__
    self._do_args_sanity_check(args)
  File "/home01/hpc72a03/.conda/envs/lightning/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 911, in _do_args_sanity_check
    assert (
AssertionError: DeepSpeed requires --deepspeed_config to specify configuration file
srun: error: gpu15: tasks 2-3: Exited with exit code 1
srun: error: gpu16: tasks 4-6: Exited with exit code 1
srun: error: gpu15: task 1: Exited with exit code 1
srun: error: gpu16: task 7: Exited with exit code 1
